import { getCurrentUser } from "@/lib/get-current-user";
import { SupplierTable } from "@/modules/supplier/supplier-table";
import { redirect } from "next/navigation";

export default async function SupplierPage() {
  const user = await getCurrentUser();

  if (!user) {
    redirect("/signin");
  }

  const initialData = [
    {
      id: "1",
      name: "ABC Logistics Sp. z o.o.",
      phone: "+48 22 123 4567",
      email: "kontakt1@abclogistics.pl",
      addressCountry: "PL",
      addressCity: "Warszawa",
      addressStreet: "ul. Marszałkowska 123",
      addressPostalCode: "00-001",
    },
    {
      id: "2",
      name: "ABC Logistics Sp. z o.o.",
      phone: "+48 22 123 4567",
      email: "kontakt2@abclogistics.pl",
      addressCountry: "PL",
      addressCity: "Warszawa",
      addressStreet: "ul. Marszałkowska 123",
      addressPostalCode: "00-001",
    },
    {
      id: "3",
      name: "LogisticPro Polska",
      phone: "+48 22 789 1234",
      email: "info@logisticpro.pl",
      addressCountry: "PL",
      addressCity: "Kraków",
      addressStreet: "ul. Długa 45",
      addressPostalCode: "30-001",
    },
    {
      id: "4",
      name: "TransWay Sp. z o.o.",
      phone: "+48 58 333 4455",
      email: "biuro@transway.pl",
      addressCountry: "PL",
      addressCity: "Gdańsk",
      addressStreet: "ul. Grunwaldzka 10",
      addressPostalCode: "80-001",
    },
    {
      id: "5",
      name: "NordicTransport",
      phone: "+48 61 444 5566",
      email: "kontakt@nordictransport.pl",
      addressCountry: "PL",
      addressCity: "Poznań",
      addressStreet: "ul. Bukowska 77",
      addressPostalCode: "60-001",
    },
    {
      id: "6",
      name: "EuroCargo Express",
      phone: "+48 42 222 3344",
      email: "office@eurocargo.pl",
      addressCountry: "PL",
      addressCity: "Łódź",
      addressStreet: "ul. Piotrkowska 200",
      addressPostalCode: "90-001",
    },
    {
      id: "7",
      name: "FastMove Logistic",
      phone: "+48 12 345 6677",
      email: "support@fastmove.pl",
      addressCountry: "PL",
      addressCity: "Kraków",
      addressStreet: "ul. Lubicz 20",
      addressPostalCode: "31-001",
    },
    {
      id: "8",
      name: "BlueLine Transport",
      phone: "+48 22 987 6543",
      email: "info@blueline.pl",
      addressCountry: "PL",
      addressCity: "Warszawa",
      addressStreet: "ul. Świętokrzyska 14",
      addressPostalCode: "00-054",
    },
    {
      id: "9",
      name: "PolTrans24",
      phone: "+48 71 555 6677",
      email: "kontakt@poltrans24.pl",
      addressCountry: "PL",
      addressCity: "Wrocław",
      addressStreet: "ul. Legnicka 50",
      addressPostalCode: "54-203",
    },
    {
      id: "10",
      name: "SpeedCargo Group",
      phone: "+48 22 333 7788",
      email: "office@speedcargo.pl",
      addressCountry: "PL",
      addressCity: "Warszawa",
      addressStreet: "ul. Jana Pawła II 15",
      addressPostalCode: "00-175",
    },
    {
      id: "11",
      name: "MegaTrans Polska",
      phone: "+48 44 222 1111",
      email: "biuro@megatrans.pl",
      addressCountry: "PL",
      addressCity: "Piotrków Trybunalski",
      addressStreet: "ul. Słowackiego 5",
      addressPostalCode: "97-300",
    },
    {
      id: "12",
      name: "GreenCargo Logistics",
      phone: "+48 22 777 8899",
      email: "contact@greencargo.pl",
      addressCountry: "PL",
      addressCity: "Warszawa",
      addressStreet: "ul. Zielona 8",
      addressPostalCode: "02-001",
    },
    {
      id: "13",
      name: "TransPol Express",
      phone: "+48 32 123 5555",
      email: "kontakt@transpol.pl",
      addressCountry: "PL",
      addressCity: "Katowice",
      addressStreet: "ul. Chorzowska 100",
      addressPostalCode: "40-101",
    },
    {
      id: "14",
      name: "LogisTech Partners",
      phone: "+48 22 654 3210",
      email: "office@logistech.pl",
      addressCountry: "PL",
      addressCity: "Warszawa",
      addressStreet: "ul. Prosta 12",
      addressPostalCode: "00-850",
    },
    {
      id: "15",
      name: "CargoMaster Poland",
      phone: "+48 94 444 7788",
      email: "info@cargomaster.pl",
      addressCountry: "PL",
      addressCity: "Koszalin",
      addressStreet: "ul. Zwycięstwa 23",
      addressPostalCode: "75-001",
    },
    {
      id: "16",
      name: "EastWest Transport",
      phone: "+48 22 110 2345",
      email: "biuro@eastwest.pl",
      addressCountry: "PL",
      addressCity: "Warszawa",
      addressStreet: "ul. Królewska 18",
      addressPostalCode: "00-065",
    },
    {
      id: "17",
      name: "PolFracht Logistics",
      phone: "+48 52 567 8899",
      email: "kontakt@polfracht.pl",
      addressCountry: "PL",
      addressCity: "Bydgoszcz",
      addressStreet: "ul. Gdańska 90",
      addressPostalCode: "85-001",
    },
    {
      id: "18",
      name: "MoveNow Transport",
      phone: "+48 22 667 8899",
      email: "support@movenow.pl",
      addressCountry: "PL",
      addressCity: "Warszawa",
      addressStreet: "ul. Targowa 55",
      addressPostalCode: "03-728",
    },
    {
      id: "19",
      name: "CargoLine Polska",
      phone: "+48 81 333 7788",
      email: "office@cargoline.pl",
      addressCountry: "PL",
      addressCity: "Lublin",
      addressStreet: "ul. Lipowa 3",
      addressPostalCode: "20-020",
    },
    {
      id: "20",
      name: "DriveFast Logistics",
      phone: "+48 22 765 4321",
      email: "kontakt@drivefast.pl",
      addressCountry: "PL",
      addressCity: "Warszawa",
      addressStreet: "ul. Aleje Jerozolimskie 20",
      addressPostalCode: "00-950",
    },
    {
      id: "21",
      name: "EuroTrans Mobility",
      phone: "+48 59 555 2233",
      email: "info@eurotrans.pl",
      addressCountry: "PL",
      addressCity: "Słupsk",
      addressStreet: "ul. Wojska Polskiego 10",
      addressPostalCode: "76-200",
    },
  ];

  return (
    <div>
      <SupplierTable initialData={initialData} />
    </div>
  );
}
